### ISSUE TITLE
New FTBApp launcher not launching properly when pined to start in windows 10

### ISSUE THREAD

**Issue by Whatsup3653** [FTBTeam/FTB-App#16]
After installing and useing the new feed the beast launcher i pined it to my start bar. It kept saying backend issues please wait or restart. Well when i went to the file it had no problems launching the launcher. I inspected the properties on the pined shortcut and it was a simple fix to remove the bin folder portion in the target path. Im not sure if im the only one with this problem but its a problem none the less.

**Comment by Cloudhunter** [comment]
Thanks for this!

**Comment by Jake-E** [comment]
This should be fixed in 1.0.7+

**Comment by ShalaxOfDellios** [comment]
This is not fixed. I am having the issue. Works fine when i launch through start bar

**Comment by squillis** [comment]
I too am having the same issue. Doing the launch from task bar, just says please wait, never loads.
