### ISSUE TITLE
[BUG] FTB Vanilla Plus 1.1.0 Server install incomplete / error

### ISSUE THREAD

**Issue by ultramoo** [FTBTeam/FTB-App#162]
**Operating System:**
OS: Windows 10, Windows Server 2012, Ubuntu 16.04, Ubuntu 18

**Describe the bug**
The latest update for FTB Vanilla Plus 1.1.0 Server install file (serverinstall_18_44) has an error when running. Does not install the Forge Library (fails to download as the file name might be incorrect) and also it does not appear to download the mod files (only config files) 

**Additional context**
See log below. This problem was tested on both Windows and Linux editions. Does not appear to be a problem for the older release of  FTB Vanilla Plus (1.0.0). Also not a problem for many other server releases. Only an  issue with  FTB Vanilla Plus 1.1.0 server.

**Log Files:**
./serverinstall_18_44
                      _                  _              _
                     | |                | |            | |
  _ __ ___   ___   __| |_ __   __ _  ___| | _____   ___| |__
 | '_ ` _ \ / _ \ / _` | '_ \ / _` |/ __| |/ / __| / __| '_ \
 | | | | | | (_) | (_| | |_) | (_| | (__|   <\__ \| (__| | | |
 |_| |_| |_|\___/ \__,_| .__/ \__,_|\___|_|\_\___(_)___|_| |_|
                       | |
                       |_|
 modpacks.ch server downloader - build 13c20a7

This will install 'FTB Vanilla+' version '1.1.0' from channel 'Release' to '/home/user/ftb/.'.
Are you sure you wish to continue? [y/n]
y
Installing 'FTB Vanilla+' version '1.1.0' from channel 'Release' to '/home/user/ftb/.'...
[1/151] Downloaded 'D3Core.cfg' to './config/D3Core/' [2087 bytes]...
[2/151] Downloaded 'JABBA.cfg' to './config/' [2503 bytes]...
[3/151] Downloaded 'Mekanism.js' to './config/INpureProjects/custom_nei_filters/' [223 bytes]...
[4/151] Downloaded 'Bibliocraft.js' to './config/INpureProjects/custom_nei_filters/' [104 bytes]...
[5/151] Downloaded 'HopperDuctMod.cfg' to './config/' [64 bytes]...
[6/151] Downloaded 'BuildCraft.js' to './config/INpureProjects/custom_nei_filters/' [216 bytes]...
[7/151] Downloaded 'INpureCore.cfg' to './config/INpureProjects/INpureCore/' [642 bytes]...
[8/151] Downloaded 'InvTweaksRules.txt' to './config/' [1352 bytes]...
[10/151] Downloaded 'BiblioCraft.cfg' to './config/' [5839 bytes]...
[9/151] Downloaded 'AppleCore.cfg' to './config/' [1160 bytes]...
[11/151] Downloaded 'ChiselTones.cfg' to './config/' [801 bytes]...
[12/151] Downloaded 'MFR.js' to './config/INpureProjects/custom_nei_filters/' [348 bytes]...
[13/151] Downloaded 'FlatSigns.cfg' to './config/' [110 bytes]...
[14/151] Downloaded 'Groups.json' to './config/D3Core/' [2 bytes]...
[15/151] Downloaded 'InvTweaksTree.txt' to './config/' [43373 bytes]...
[16/151] Downloaded 'CarpentersBlocks.cfg' to './config/' [3143 bytes]...
[17/151] Downloaded 'vanilla.js' to './config/INpureProjects/custom_nei_filters/' [244 bytes]...
[18/151] Downloaded 'ExtraUtilities.js' to './config/INpureProjects/custom_nei_filters/' [377 bytes]...
[19/151] Downloaded 'mainmenu.json' to './config/CustomMainMenu/' [7537 bytes]...
[20/151] Downloaded 'LLadders.cfg' to './config/' [657 bytes]...
[21/151] Downloaded 'AppliedEnergistics2.js' to './config/INpureProjects/custom_nei_filters/' [142 bytes]...
[22/151] Downloaded 'Players.json' to './config/D3Core/' [2 bytes]...
[23/151] Downloaded 'Tcon.js' to './config/INpureProjects/custom_nei_filters/' [195 bytes]...
[24/151] Downloaded 'ThermalExpansion.js' to './config/INpureProjects/custom_nei_filters/' [126 bytes]...
[25/151] Downloaded 'debug.log' to './config/INpureProjects/logs/' [12093 bytes]...
[26/151] Downloaded 'ForgeMicroblock.js' to './config/INpureProjects/custom_nei_filters/' [311 bytes]...
[27/151] Downloaded 'custom_nei_filters.cfg' to './config/INpureProjects/custom_nei_filters/' [345 bytes]...
[28/151] Downloaded 'Bootstrap.js' to './config/INpureProjects/custom_nei_filters/' [309 bytes]...
[29/151] Downloaded 'CodeChickenCore.cfg' to './config/' [832 bytes]...
[30/151] Downloaded 'materials.json' to './config/D3Core/' [2 bytes]...
[31/151] Downloaded 'nei_filters.toc' to './config/INpureProjects/custom_nei_filters/' [465 bytes]...
[32/151] Downloaded 'InvTweaks.cfg' to './config/' [675 bytes]...
[33/151] Downloaded 'NEIAddons.cfg' to './config/' [472 bytes]...
[34/151] Downloaded 'client.cfg' to './config/NEI/' [1314 bytes]...
[35/151] Downloaded 'MUD.cfg' to './config/' [487 bytes]...
[36/151] Downloaded 'Morpheus.cfg' to './config/' [365 bytes]...
[37/151] Downloaded 'GrassDrops.txt' to './config/agricraft/' [405 bytes]...
[38/151] Downloaded 'etfuturum.cfg' to './config/' [689 bytes]...
[39/151] Downloaded 'SpiceOfLife.cfg' to './config/' [6654 bytes]...
[40/151] Downloaded 'modules.cfg' to './config/railcraft/' [1262 bytes]...
[41/151] Downloaded 'chisel.cfg' to './config/' [7405 bytes]...
[42/151] Downloaded 'example-food-group.json' to './config/SpiceOfLife/' [1780 bytes]...
[43/151] Downloaded 'MrTJPCore.cfg' to './config/' [599 bytes]...
[44/151] Downloaded 'PluginMetrics.cfg' to './config/' [240 bytes]...
[45/151] Downloaded 'jacb.cfg' to './config/' [221 bytes]...
[46/151] Downloaded 'Mutations.txt' to './config/agricraft/' [5963 bytes]...
[47/151] Downloaded 'props.cfg' to './config/' [508 bytes]...
[48/151] Downloaded 'eula.txt' to './' [184 bytes]...
[49/151] Downloaded 'biome_textures.json' to './config/antiqueatlas/' [1533 bytes]...
[50/151] Downloaded 'denseores.cfg' to './config/' [2024 bytes]...
[51/151] Downloaded 'neiintegration.cfg' to './config/' [2909 bytes]...
[52/151] Downloaded 'items.cfg' to './config/railcraft/' [2801 bytes]...
[53/151] Downloaded 'SeedBlackList.txt' to './config/agricraft/' [188 bytes]...
[54/151] Downloaded 'Mantle.cfg' to './config/SlimeKnights/' [354 bytes]...
[55/151] Downloaded 'StevesWorkshop.cfg' to './config/' [1173 bytes]...
[56/151] Downloaded 'SeedTiers.txt' to './config/agricraft/' [333 bytes]...
[57/151] Downloaded 'SoilWhitelist.txt' to './config/agricraft/' [437 bytes]...
[58/151] Downloaded 'multipart.cfg' to './config/' [248 bytes]...
[59/151] Downloaded 'Natura.cfg' to './config/' [3342 bytes]...
[60/151] Downloaded 'StorageDrawers.cfg' to './config/' [2057 bytes]...
[61/151] Downloaded 'blocks.cfg' to './config/railcraft/' [10421 bytes]...
[62/151] Downloaded 'compactstorage.cfg' to './config/' [2356 bytes]...
[63/151] Downloaded 'Configuration.cfg' to './config/agricraft/' [4272 bytes]...
[64/151] Downloaded 'texture_sets.json' to './config/antiqueatlas/' [154 bytes]...
[65/151] Downloaded 'endercompass.cfg' to './config/' [65 bytes]...
[66/151] Downloaded 'Natura-Dynamic.json' to './config/' [235 bytes]...
[67/151] Downloaded 'SpreadChancesOverrides.txt' to './config/agricraft/' [360 bytes]...
[68/151] Downloaded 'ProjectRed.cfg' to './config/' [2893 bytes]...
[69/151] Downloaded 'marker_textures.json' to './config/antiqueatlas/' [813 bytes]...
Jun 09, 2020 3:07:40 AM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: version.json unable to get content length from HTTP headers!
[70/151] Downloaded 'battlegear2.cfg' to './config/' [4497 bytes]...
[71/151] Downloaded 'forgeChunkLoading.cfg' to './config/' [2025 bytes]...
[72/151] Downloaded 'railcraft.cfg' to './config/railcraft/' [17889 bytes]...
[73/151] Downloaded 'version.json' to './' [-1 bytes]...
[74/151] Downloaded 'forge.cfg' to './config/' [2364 bytes]...
[75/151] Downloaded 'tile_textures.json' to './config/antiqueatlas/' [951 bytes]...
[76/151] Downloaded 'TorchTools.cfg' to './config/' [206 bytes]...
[77/151] Downloaded 'Waila.cfg' to './config/' [8063 bytes]...
[78/151] Downloaded 'harvestcraft.cfg' to './config/' [6880 bytes]...
[79/151] Downloaded 'Ztones.cfg' to './config/' [1044 bytes]...
[80/151] Downloaded 'microblocks.cfg' to './config/' [488 bytes]...
[81/151] Downloaded 'splash.properties' to './config/' [339 bytes]...
[82/151] Downloaded 'tileids.json' to './config/antiqueatlas/' [691 bytes]...
Jun 09, 2020 3:07:41 AM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: forge-1.7.10-1.7.10-installer.zip error 404: Not Found!
[82/151] Unable to download: File does not exist at URL.
java.io.FileNotFoundException: File does not exist at URL.
        at net.creeperhost.creeperlauncher.api.DownloadableFile.prepare(DownloadableFile.java:126)
        at net.creeperhost.ftbserverdownloader.ServerVersion.lambda$install$2(ServerVersion.java:154)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
[83/151] Downloaded 'forge-1.7.10-1.7.10-installer.zip' to './' [14 bytes]...
[83/151] Finished.
Invoking forge 1.7.10 installer.
================= FORGE INSTALL BEGINS =================
Error: Unable to access jarfile /home/user/ftb/./forge-1.7.10-1.7.10-installer.zip
=================  FORGE INSTALL ENDS  =================
Pack install Finished.

**Comment by Rushmead** [comment]
This should now be fixed, it was an misconfiguration of the modpack in the API. It may take some time for the cache to clear properly.

**Comment by ultramoo** [comment]
It does now download and install forge correctly, however the mods folder is still missing.
Only appears to download the config folder for the modpack.

**Comment by Sunekaer** [comment]
Okay can you redownload the server installer and test again, there was deployed a new version last night there should fix that @ultramoo

**Comment by ultramoo** [comment]
Still missing mod files. 

I've completely deleted and redownloaded Vanilla Plus 1.1.0 server file.
It still appears to download the file: serverinstall_18_44.exe
When I run this, it downloads config folder, forge, and install forge library but there are no mods folder.

Nothing in the logs that state an error.
![mods missing](https://user-images.githubusercontent.com/8270707/84843945-9b8f6f00-b08c-11ea-87f7-0eb282e4936d.PNG)
[downloader.log](https://github.com/FTBTeam/FTB-App/files/4789833/downloader.log)
[installer.log](https://github.com/FTBTeam/FTB-App/files/4789834/installer.log)

**Comment by Sunekaer** [comment]
Okay thanks, i have found the issue and we are looking in to fix it

**Comment by Sunekaer** [comment]
Sorry about the waiting time, issue should be fixed now could i get you to test?

**Comment by ultramoo** [comment]
Test complete. All files correctly downloaded and working as expected. Thanks!
