### ISSUE TITLE
[Bug] Unable to change Instance Location

### ISSUE THREAD

**Issue by 016Nojr** [FTBTeam/FTB-App#194]
**Operating System:**
OS: Win 10

![info](https://user-images.githubusercontent.com/8192699/86547869-abd39500-bf3a-11ea-9b6b-c3274db08594.PNG)

**Log Files:**
https://pste.ch/ikemehagim

**Describe the bug**
When I try changing install location for instances it says it doesnt have write access in the new location, even though it's under the same folder I also have Twitch instances in, I have also tried running the app in admin mode. The current location only holds a fresh Interactions 2.0 install.
![info2](https://user-images.githubusercontent.com/8192699/86547976-0836b480-bf3b-11ea-83ab-1b8cc83b85df.PNG)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Launcher
2. Change Instance Location
3. See Error

**Expected behaviour**
The instance location to change

**Comment by ariosos** [comment]
Can confirm I'm having this issue, too.  I also tried reinstalling, and removing the FTB Interactions 2.0 instance (made a backup, of course!). You also can't click "No" on the confirmation dialog, and the confirmation dialog pops up even if you click in another textbox after making a change.

**Comment by Sinhika** [comment]
I have a related issue--if I change the instance location, and hit yes, it accepts it--and then apparently ignores it. When I close and re-open the app, the instance location is right back to the default, which, on my computer, is an unacceptable location. (C drive is a bit crowded).

**Comment by Cloudhunter** [comment]
I will add more logging in order to try and diagnose these issues - I initially disabled some logging as they were being reported as bugs despite not being, but I will add some back.

Can any of the people replying please provide some logs too?

**Comment by Cloudhunter** [comment]
Here is a new build with more logging. If you could try it out and let me know your results, and if it fails, provide me with your logs, it would be appreciated.

http://apps.modpacks.ch/FTBApp/develop/202007121939-8248c89f69-develop/FTBA_windows-x64_202007121939-8248c89f69-develop.exe

**Comment by 016Nojr** [comment]
@Cloudhunter Just tried with the version you provided, fresh install and no packs installed.

[Log](https://pste.ch/ufihiqidaj)

**Comment by Cloudhunter** [comment]
New build incoming which should fix this issue... auto update should work eventually, but I'll provide a link in about 20 minutes or so.

**Comment by Cloudhunter** [comment]
https://app.modpacks.ch/FTBApp/develop/202007122101-fa74e7bb6f-develop/FTBA_windows-x64_202007122101-fa74e7bb6f-develop.exe

**Comment by 016Nojr** [comment]
Still broken for me (Autoupdate happened when launching)

[Log](https://pste.ch/abafolitic)

**Comment by Cloudhunter** [comment]
New build incoming, will post when done (if autoupdate doesn't happen first)

**Comment by Cloudhunter** [comment]
https://app.modpacks.ch/FTBApp/develop/202007122125-e4937a0a9f-develop/FTBA_windows-x64_202007122125-e4937a0a9f-develop.exe

**Comment by Cloudhunter** [comment]
(Also, thanks so much for testing this!)

**Comment by 016Nojr** [comment]
No problem, [Still broken for me](https://pste.ch/vumarupira)

**Comment by Cloudhunter** [comment]
Ok, I now know what the issue is (other than me being an idiot). New build coming after I've tested it.

**Comment by Cloudhunter** [comment]
This should fix the issues. Hot off the ~press~ build box!

 https://apps.modpacks.ch/FTBApp/develop/202007122354-7bba226a39-develop/FTBA_windows-x64_202007122354-7bba226a39-develop.exe

**Comment by Sinhika** [comment]
Okay, I figured another thing out: if you don't download a modpack, the FTBApp does not respect or save the instances location. If I do download a modpack, it keeps the new instances location. This is not the best behavior. It should respect the instances location whether or not you've downloaded a modpack yet.

Also, if you try to set the instances location to a directory with a .localcache in it, like oh, if you set the instances location, and opened up the app next time to find out that the app didn't save the instance location, and try to reset set it to your preferred location, it will error and claim it can't write to that location. Maybe it shouldn't be trying to overwrite a .localcache that already exists? Maybe it should NOT treat an existing .localcache as an error, either? Maybe the error message should be more informative?

**Comment by Cloudhunter** [comment]
> Okay, I figured another thing out: if you don't download a modpack, the FTBApp does not respect or save the instances location. If I do download a modpack, it keeps the new instances location. This is not the best behavior. It should respect the instances location whether or not you've downloaded a modpack yet.

That is what it is supposed to do. I will make sure it does that.

> Maybe it shouldn't be trying to overwrite a .localcache that already exists? Maybe it should NOT treat an existing .localcache as an error, either?

There's a lot of maybe's here, but I agree that anything to do with the ".localCache" should not be treated as an error.

> Maybe the error message should be more informative?

It is currently written to the log - due to the amount of things that could go wrong, getting it all in the UI could be difficult.

**Comment by Cloudhunter** [comment]
https://apps.modpacks.ch/FTBApp/develop/202007130144-3829e850c8-develop/FTBA_windows-x64_202007130144-3829e850c8-develop.exe

I wasn't able to reproduce this:

> Okay, I figured another thing out: if you don't download a modpack, the FTBApp does not respect or save the instances location. If I do download a modpack, it keeps the new instances location. This is not the best behavior. It should respect the instances location whether or not you've downloaded a modpack yet.

I can only presume it works in this latest build. Please test and let me know if things are now working better for you.

**Comment by ariosos** [comment]
I tried it with the FTBA_windows-x64_202007121939-8248c89f69-develop.exe and it did set it to the new location successfully (but, this was before I downloaded a pack). Just tried installing new modpacks (Material Energy 5 and FTB Academy) and it gave a SHA1 mismatch error, but the packs are still in the list. The modpack seems to load, though (broken main menu textures for ME5, but it works).
[files.log](https://github.com/FTBTeam/FTB-App/files/4910274/files.log)
[installation.log](https://github.com/FTBTeam/FTB-App/files/4910275/installation.log)

**Comment by Cloudhunter** [comment]
Can you please provide the logs from the option in the Settings page to upload logs too? I do not believe the SHA1 issue is related, but I want to be sure.

**Comment by ariosos** [comment]
https://pste.ch/oyilixinut

**Comment by Sinhika** [comment]
Further testing with the new version (note I am updating an existing install, not doing a new install each time) FTBA_windows-x64_202007130144-3829e850c8-develop.exe:

- It remembers the previous instance location setting.
- when I tell it to set the location somewhere else, and then try to say "NO", to the "Are you sure?"-type prompt, the prompt does not exit or carry out any action that I can see.
- It does respect and remember the instance location setting even if there are no modpacks installed there (i.e., at a fresh location)

**Comment by Cloudhunter** [comment]
There was a slight regression in the version which made it into release which means it might not work for all users, but this should be resolved in the next release.
