### ISSUE TITLE
MC Launcher doesn't open after clicking play

### ISSUE THREAD

**Issue by lifeofchrome** [FTBTeam/FTB-App#7]
After downloading FTB Omnia and clicking the play icon, nothing happens/the MC launcher doesn't launch.

**Steps to Recreate**
1. Download a modpack
2. Press the play icon
3. Observe that nothing happens

**Expected Behavior**
Presumably, the Minecraft launcher would launch with a profile to play FTB Omnia.

**System/Environment Information**
OS: Linux, elementary OS 5.1.2, Built on Ubuntu 18.04.3
Java: OpenJDK 1.8.0_242
FTB App: v1.0.2
- Settings: Default RAM: 7GB, FTB Omnia RAM: 7GB

**Additional context**
Potentially relevant log file: https://gist.github.com/lifeofchrome/7854e5a62c6d5c526e4b1ff7576225fe
Discord conversation: https://discordapp.com/channels/372448486723158016/695329867037933609/695338181087723610

**Comment by Cloudhunter** [comment]
I'm seeing a LOT of 404's in your log which could potentially be explaining this. We have recently done some cache changes which may alleviate some of this.

Can you try installing the pack again?

**Comment by lifeofchrome** [comment]
I tried deleting and reinstalling the pack again, and nothing happened when I clicked play. Unfortunately I don't have logs when doing so because after that I thought I'd try making a fresh install of the FTB App. When doing this, I tried to install FTB Omnia again and this time, it seemed to get stuck indefinitely on "Creating environment...". At this stage the latest entry in `error.log` was 
    `INFO: Starting download of the vanilla launcher`
This continued for over an hour. Further attempts to close the app and try re-downloading also resulted in getting stuck there.

Here is my current error.log and launcher.log: https://gist.github.com/lifeofchrome/3292180de2edf24d92e5cf5e9d6f134e

**Comment by Jake-E** [comment]
Does this still happen for you in the latest version of the app?

**Comment by lifeofchrome** [comment]
I think it's fixed now, thanks!

**Comment by viveleroi** [comment]
Not fixed, it's happening to me on a fresh download and install of the launcher today. Trying to download the direwolf20 1.12.2 pack and it's been stuck on "creating environment" for two hours. I have other players who reported the same.

**Comment by Rushmead** [comment]
@viveleroi Please provide information such as your current version of the App (found on settings page), what operating system you are on, logs from the app (also found on the settings page)
