### ISSUE TITLE
[Problem]: FTB APP stuck on "Waiting for response..." after login with Microsoft account.

### ISSUE THREAD

**Issue by Chowtick** [FTBTeam/FTB-App#755]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Debug Code

FTB-DBGLEZUBIPIGU

### Describe the bug

I Clicked on an instance and told me there was an error validating Microsoft account. Removed my account and tried re-login, however every time i log in it tells me "You're in!" but the FTB app is stuck at "Waiting for response..."

### Steps to reproduce

1. Open FTB APP
2. Either attempt to login with Microsoft account
3. Log into Microsoft account through browser
4. Once you've successfully logged in through browser, go back to FTB APP and it will still say "Waiting for response..."
5. 1 hour and 20 minutes later, its still waiting for a response.

### Expected behaviour

I expected once i successfully logged into my Microsoft account VIA browser, my account would be added to FTB APP and I would be able to play Minecraft.

### Additional information

The game was working fine the last couple days. I noticed yesterday the ICON was updated and when i went to play this morning i was unable to play the game.

### Information

- [X] I have provided as much information as possible

**Comment by ncecil** [comment]
Same problem here. Logs make it look like the app is getting rate limited by Microsoft's oauth endpoint:

```
[14:40:53.294] [ForkJoinPool-1-worker-1/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: 429|https://api.minecraftservices.com/launcher/login responded with: {"path":"/launcher/login"}
[14:40:53.294] [ForkJoinPool-1-worker-1/ERROR] [net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler]: Error handling message
```

Full logs: https://pste.ch/oqiboqofoq

Do all FTB clients use the same API token?

**Comment by Auryannae** [comment]
Same stuck on waiting for a response

**Comment by pha3l** [comment]
Same on mac, logs: https://pste.ch/ruheyixice

**Comment by shinji257** [comment]
Same and other clients are impacted as well.  This is not specific to FTB App.

**Comment by Araellah** [comment]
Same thing has been happening to me on Mac

**Comment by JasonWBridgeTown** [comment]
ditto.

**Comment by Darakilas** [comment]
same thing for me also

**Comment by NontasGR** [comment]
Same problem here

**Comment by Petrakous** [comment]
Try using vpn it fixxed it for me. Im using Hotspot Shield

**Comment by ncecil** [comment]
VPN also resolved the issue for me. Maybe MS has some kind of overly aggressive DDoS protection going?

**Comment by LandonCalling** [comment]
This is also a problem on the linux client

**Comment by SuperNova1440** [comment]
using a VPN also worked for me

**Comment by Dankwiz2017** [comment]
VPN did not work for me

**Comment by LandonCalling** [comment]
using a vpn worked for me as long as I didn't choose a location in the US

**Comment by shinji257** [comment]
It works randomly.  I usually keep trying with small gaps in between each attempt and eventually it goes through.  No VPN required.  I think using the VPN and having it work is just coincidence.

**Comment by EpicWhiteWolf** [comment]
same problem on windows 10, i'm so sick of all these fucking apps being absolute dog shit

**Comment by shinji257** [comment]
> same problem on windows 10, i'm so sick of all these fucking apps being absolute dog shit

Before you blame the app please note that this affects all launchers.  This is the Minecraft session servers applying rate limiting for some reason and so authentication is intermittent at best.  It would be the nice though if the app gave better visual feedback than it just seeming to get stuck.

**Comment by SlaaneshiCultist0** [comment]
Yeah, at this point I've tried quite literally everything suggested so far - VPN and spamming log-ins. Impossible to actually log in on my side. Hopefully this is resolved soon.

**Comment by Darakilas** [comment]
Logged normally now.

**Comment by GalacticTurtle01** [comment]
Yeah i've been having issues as well.

**Comment by NontasGR** [comment]
The Issue has been fixed I suppose, because I haven't encountered it for some weeks now

**Comment by GalacticTurtle01** [comment]
> The Issue has been fixed I suppose, because I haven't encountered it for some weeks now

It hasn't been for me as it still shows the waiting for response page multiple times

**Comment by MichaelHillcox** [comment]
This was due to Microsoft authentication issues. If this is still happening, please use our discord for support.
