### ISSUE TITLE
app won't authenticate

### ISSUE THREAD

**Issue by fedorne13** [FTBTeam/FTB-App#960]
### What Operating System

Windows 11

### Debug Code

FTB-AUTH-000005

### Describe the bug

It looks like you own XBox Gamepass for PC or have only recently bought Minecraft Java Edition, this is great! Unfortunately, before we can log you in, you'll need to start the Vanilla Launcher at least once and run Minecraft. Once you have done this, try again

### Steps to reproduce

I've run minecraft from the vanilla launcher but continue to get error. I've tried logging out and in with both vanilla launcher and ftb app with no success.

### Expected behaviour

It should authenticate

**Comment by manmaed** [comment]
Please make you have logged in to the vanilla Launcher and launched minecraft

**Comment by manmaed** [comment]
@suravit0

**Comment by fedorne13** [comment]
I launched Minecraft through the vanilla launcher.

**Comment by bajkhe992** [comment]
@fedorne13 you need to create a world too. Doing that just fixed it for me.

**Comment by MichaelHillcox** [comment]
Looks like this should be solved. Thanks for the info @bajkhe992 we'll give this a test and update the message if needed

**Comment by fedorne13** [comment]
This didn't work either. Any other suggestions?

**Comment by Etomia** [comment]
Still have this issue, tried everything I've found online, Minecraft is tied to the right account and it shows up as should in the xbox app, have played vanilla many times before, but completely unable to login to the ftb app.
